<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ng_desktop" failures="1" tests="3" name="Test" time="0.039" errors="0" timestamp="2023-06-12T23:22:32 EDT">
  <testcase classname="testnglistenerexample.TestNgListnerExample1" name="testWeb1" time="0.007"/>
  <testcase classname="testnglistenerexample.TestNgListnerExample1" name="testWeb2" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testnglistenerexample.TestNgListnerExample1.testWeb2(TestNgListnerExample1.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testWeb2 -->
  <testcase classname="testnglistenerexample.TestNgListnerExample1" name="testWeb3" time="0.0">
    <skipped/>
  </testcase> <!-- testWeb3 -->
</testsuite> <!-- Test -->
